/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.CategoriaDAO;
import enums.Embalagens;
import enums.Tamanhos;
import java.awt.Font;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Categoria;

/**
 *
 * @author BeCunha7
 */
public class FrmCadastroCategoria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCadastroCategoria.class.getName());

    private final CategoriaDAO dao = new CategoriaDAO();
    private int categoriaId = -1;

    /**
     * Creates new form FrmCadastroCategoria
     */
    public FrmCadastroCategoria() {
        initComponents();
        configurarTela();
        popularCombos();
    }

    public FrmCadastroCategoria(Categoria categoria) {
        initComponents();
        configurarTela();
        popularCombos();
        carregarCategoria(categoria);
    }

    private void configurarTela() {
        setTitle("Cadastro de Categoria");
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(250, 250, 250));
        getRootPane().setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18));

        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 18));
        JLNomeCategoria.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        JLEmbalagem.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        JLTamanho.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        JTFNomeCategoria.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        JTFNomeCategoria.setColumns(24);
        jComboBox1.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jComboBox2.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        java.awt.Font buttonFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14);
        JBSalvar.setFont(buttonFont);
        JBLimpar.setFont(buttonFont);
        JBFechar.setFont(buttonFont);
        JBSalvar.setOpaque(true);
        JBSalvar.setBackground(new java.awt.Color(33, 150, 243));
        JBSalvar.setForeground(java.awt.Color.WHITE);
        JBLimpar.setOpaque(true);
        JBLimpar.setBackground(new java.awt.Color(96, 125, 139));
        JBLimpar.setForeground(java.awt.Color.WHITE);
        JBFechar.setOpaque(true);
        JBFechar.setBackground(new java.awt.Color(244, 67, 54));
        JBFechar.setForeground(java.awt.Color.WHITE);
    }

    private void popularCombos() {
        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] {"LATA", "VIDRO", "PLASTICO"}));
        jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] {"PEQUENO", "MÉDIO", "GRANDE"}));
    }

    private void carregarCategoria(Categoria categoria) {
        categoriaId = categoria.getIdCategoria();
        JTFNomeCategoria.setText(categoria.getNome());
        jComboBox1.setSelectedItem(categoria.getEmbalagem().name());
        jComboBox2.setSelectedItem(categoria.getTamanho().name());
        JBSalvar.setText("Atualizar");
    }

    private void limparCampos() {
        categoriaId = -1;
        JTFNomeCategoria.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        JTFNomeCategoria.requestFocus();
        JBSalvar.setText("Salvar");
    }

    private void salvarCategoria() {
        String nome = JTFNomeCategoria.getText().trim();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira o nome da categoria!", "Aviso do Sistema", JOptionPane.WARNING_MESSAGE);
            JTFNomeCategoria.requestFocus();
            return;
        }

        Categoria categoria = new Categoria();
        categoria.setIdCategoria(categoriaId);
        categoria.setNome(nome);
        categoria.setEmbalagem(Embalagens.valueOf(jComboBox1.getSelectedItem().toString()));
        categoria.setTamanho(Tamanhos.valueOf(jComboBox2.getSelectedItem().toString()));

        if (categoriaId <= 0) {
            dao.cadastrar(categoria);
        } else {
            dao.atualizar(categoria);
        }

        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLNomeCategoria = new javax.swing.JLabel();
        JTFNomeCategoria = new javax.swing.JTextField();
        JLEmbalagem = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        JLTamanho = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        JBSalvar = new javax.swing.JButton();
        JBLimpar = new javax.swing.JButton();
        JBFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cadastro de Categoria");

        JLNomeCategoria.setText("Nome:");

        JLEmbalagem.setText("Embalagem:");

        JLTamanho.setText("Tamanho:");

        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(this::JBSalvarActionPerformed);

        JBLimpar.setText("Limpar");
        JBLimpar.addActionListener(this::JBLimparActionPerformed);

        JBFechar.setText("Fechar");
        JBFechar.addActionListener(this::JBFecharActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JLTamanho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JLNomeCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(JTFNomeCategoria))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JLEmbalagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(JBSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(JBLimpar)
                .addGap(40, 40, 40)
                .addComponent(JBFechar)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNomeCategoria)
                    .addComponent(JTFNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLEmbalagem)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLTamanho)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSalvar)
                    .addComponent(JBLimpar)
                    .addComponent(JBFechar))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        salvarCategoria();
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void JBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBFecharActionPerformed

    private void JBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_JBLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FrmCadastroCategoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBFechar;
    private javax.swing.JButton JBLimpar;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JLabel JLEmbalagem;
    private javax.swing.JLabel JLNomeCategoria;
    private javax.swing.JLabel JLTamanho;
    private javax.swing.JTextField JTFNomeCategoria;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
