/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package visao;

import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author genti
 */
public class FrmMovimentacao extends javax.swing.JPanel implements java.beans.Customizer {
    
  public FrmMovimentacao() {
    initComponents();
    // adiciona campo de quantidade manualmente
    txtQtd.setBounds(10, 80, 120, 25);
    add(txtQtd);
}
    
    public void setObject(Object bean) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbProdutos = new javax.swing.JComboBox<>();
        rbENTRADA = new javax.swing.JRadioButton();
        rbSAÍDA = new javax.swing.JRadioButton();
        jBSALVAR = new javax.swing.JButton();
        txtQtd = new javax.swing.JTextField();

        cmbProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rbENTRADA.setText("ENTRADA");

        rbSAÍDA.setText("SAÍDA");

        jBSALVAR.setText("SALVAR");
        jBSALVAR.addActionListener(this::jBSALVARActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBSALVAR)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(rbENTRADA))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(rbSAÍDA))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbENTRADA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSAÍDA)
                .addGap(34, 34, 34)
                .addComponent(cmbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jBSALVAR)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSALVARActionPerformed
private void jBSALVARActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        String produtoNome = cmbProdutos.getSelectedItem().toString();
        int qtd = Integer.parseInt(txtQtd.getText().trim());
        String tipo = rbENTRADA.isSelected() ? "ENTRADA" : "SAIDA";

        // Busca o ID do produto pelo nome
        java.util.List<modelo.Produto> lista = new dao.ProdutoDAO().listar();
        int idProduto = -1;
        modelo.Produto prodSelecionado = null;
        for (modelo.Produto p : lista) {
            if (p.getNome().equals(produtoNome)) {
                idProduto = p.getId();
                prodSelecionado = p;
                break;
            }
        }
        if (idProduto == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Produto não encontrado.");
            return;
        }

        modelo.Movimentacao mov = new modelo.Movimentacao(idProduto,
            new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()),
            qtd, tipo);
        new dao.MovimentacaoDAO().registrar(mov);

        // Alerta de estoque
        if ("ENTRADA".equals(tipo) && prodSelecionado != null
                && (prodSelecionado.getQuantidade() + qtd) > prodSelecionado.getQntdMax()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "⚠️ ATENÇÃO: Estoque acima da quantidade MÁXIMA!");
        } else if ("SAIDA".equals(tipo) && prodSelecionado != null
                && (prodSelecionado.getQuantidade() - qtd) < prodSelecionado.getQntdMin()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "⚠️ ATENÇÃO: Estoque abaixo da quantidade MÍNIMA!");
        }

        carregarProdutos(); // recarrega combo
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Digite um número válido na quantidade.");
    }
}

    }//GEN-LAST:event_jBSALVARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbProdutos;
    private javax.swing.JButton jBSALVAR;
    private javax.swing.JRadioButton rbENTRADA;
    private javax.swing.JRadioButton rbSAÍDA;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables

    private static class rbEntrada {

        private static boolean isSelected() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public rbEntrada() {
        }
    }
}
