/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package visao;

import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author genti
 */
public class FrmMovimentacao extends javax.swing.JPanel implements java.beans.Customizer {
    
    /**
     * Creates new customizer FrmMovimentacao
     */
    public FrmMovimentacao() {
        initComponents();
    }
    
    public void setObject(Object bean) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbProdutos = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JLabel();
        rbENTRADA = new javax.swing.JRadioButton();
        rbSAÍDA = new javax.swing.JRadioButton();
        jBSALVAR = new javax.swing.JButton();

        cmbProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtQuantidade.setText("QUANTIDADE:");

        rbENTRADA.setText("ENTRADA");

        rbSAÍDA.setText("SAÍDA");

        jBSALVAR.setText("SALVAR");
        jBSALVAR.addActionListener(this::jBSALVARActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(cmbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtQuantidade))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbENTRADA))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbSAÍDA)))
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBSALVAR)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(txtQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbENTRADA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSAÍDA)
                .addGap(1, 1, 1)
                .addComponent(cmbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jBSALVAR)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSALVARActionPerformed
try {
    // 1. Pega o que o usuário digitou na tela
    String produtoEscolhido = cmbProdutos.getSelectedItem().toString();
    int qtdDigitada = Integer.parseInt(txtQuantidade.getText());
    boolean tipoEntrada = rbEntrada.isSelected(); 

    // 2. Conecta no banco (AJUSTE "conexao.Conexao" PARA A SUA CLASSE DE BANCO)
    java.sql.Connection conn = conexao.Conexao.getConexao();
    
    if (tipoEntrada) {
        // Lógica Simplificada de ENTRADA (Soma no banco)
        java.sql.PreparedStatement st = conn.prepareStatement("UPDATE produto SET quantidade_estoque = quantidade_estoque + ? WHERE nome = ?");
        st.setInt(1, qtdDigitada);
        st.setString(2, produtoEscolhido);
        st.executeUpdate();
        
        // Exibe o alerta de MÁXIMO 
        javax.swing.JOptionPane.showMessageDialog(null, "Entrada Salva! \n⚠️ ALERTA: Verifique se o estoque não ultrapassou a Quantidade MÁXIMA.");
        
    } else {
        // Lógica Simplificada de SAÍDA (Subtrai no banco)
        java.sql.PreparedStatement st = conn.prepareStatement("UPDATE produto SET quantidade_estoque = quantidade_estoque - ? WHERE nome = ?");
        st.setInt(1, qtdDigitada);
        st.setString(2, produtoEscolhido);
        st.executeUpdate();
        
        // Exibe o alerta de MÍNIMO
        javax.swing.JOptionPane.showMessageDialog(null, "Saída Salva! \n⚠️ ALERTA: Verifique se o produto não ficou abaixo da Quantidade MÍNIMA.");
    }
    
} catch (HeadlessException | NumberFormatException | SQLException erro) {
    javax.swing.JOptionPane.showMessageDialog(null, "Ops, deu um erro. Verifique se digitou apenas números na quantidade!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jBSALVARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbProdutos;
    private javax.swing.JButton jBSALVAR;
    private javax.swing.JRadioButton rbENTRADA;
    private javax.swing.JRadioButton rbSAÍDA;
    private javax.swing.JLabel txtQuantidade;
    // End of variables declaration//GEN-END:variables

    private static class rbEntrada {

        private static boolean isSelected() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public rbEntrada() {
        }
    }
}
