/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author PICHAU
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        configurarTela();
    }

    private void configurarTela() {
        setTitle("Controle de Estoque");
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(245, 245, 245));
        getRootPane().setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18));

        JLTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        JLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        java.awt.Font buttonFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14);
        JBCadastroCategoria.setFont(buttonFont);
        JBCadastroProduto.setFont(buttonFont);
        JBCadastroMovimentacao.setFont(buttonFont);
        JBGerenciaCategoria.setFont(buttonFont);
        JBGerenciaProduto.setFont(buttonFont);
        JBGerenciaMovimentacao.setFont(buttonFont);
        JBRelatorios.setFont(buttonFont);

        JBRelatorios.setToolTipText("Visualizar relatórios do estoque");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLTitulo = new javax.swing.JLabel();
        JBCadastroCategoria = new javax.swing.JButton();
        JBCadastroMovimentacao = new javax.swing.JButton();
        JBCadastroProduto = new javax.swing.JButton();
        JBGerenciaCategoria = new javax.swing.JButton();
        JBGerenciaProduto = new javax.swing.JButton();
        JBGerenciaMovimentacao = new javax.swing.JButton();
        JBRelatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLTitulo.setText("Controle de Estoque");

        JBCadastroCategoria.setText("Cadastrar Categoria");
        JBCadastroCategoria.addActionListener(this::JBCadastroCategoriaActionPerformed);

        JBCadastroMovimentacao.setText("Cadastrar Movimentação");
        JBCadastroMovimentacao.addActionListener(this::JBCadastroMovimentacaoActionPerformed);

        JBCadastroProduto.setText("Cadastrar Produto");
        JBCadastroProduto.addActionListener(this::JBCadastroProdutoActionPerformed);

        JBGerenciaCategoria.setText("Gerenciar Categoria");
        JBGerenciaCategoria.addActionListener(this::JBGerenciaCategoriaActionPerformed);

        JBGerenciaProduto.setText("Gerenciar Produto");
        JBGerenciaProduto.addActionListener(this::JBGerenciaProdutoActionPerformed);

        JBGerenciaMovimentacao.setText("Gerenciar Movimentação");
        JBGerenciaMovimentacao.addActionListener(this::JBGerenciaMovimentacaoActionPerformed);

        JBRelatorios.setText("Relatórios");
        JBRelatorios.addActionListener(this::JBRelatoriosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBCadastroCategoria)
                    .addComponent(JBGerenciaCategoria))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(JLTitulo)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(JBCadastroMovimentacao))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JBGerenciaProduto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JBGerenciaMovimentacao)))
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JBCadastroProduto)
                                .addGap(239, 239, 239))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(JBRelatorios)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCadastroCategoria)
                    .addComponent(JBCadastroProduto)
                    .addComponent(JBCadastroMovimentacao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBGerenciaCategoria)
                    .addComponent(JBGerenciaProduto)
                    .addComponent(JBGerenciaMovimentacao))
                .addGap(40, 40, 40)
                .addComponent(JBRelatorios)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCadastroCategoriaActionPerformed
        FrmCadastroCategoria telaCadastroCategoria = new FrmCadastroCategoria();
        telaCadastroCategoria.setVisible(true);
    }//GEN-LAST:event_JBCadastroCategoriaActionPerformed

    private void JBGerenciaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGerenciaCategoriaActionPerformed
        FrmGerenciaCategoria telaCategoria = new FrmGerenciaCategoria();
        telaCategoria.setVisible(true);    }//GEN-LAST:event_JBGerenciaCategoriaActionPerformed

    private void JBGerenciaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGerenciaProdutoActionPerformed
        FrmGerenciaProduto telaProduto = new FrmGerenciaProduto();
        telaProduto.setVisible(true);     }//GEN-LAST:event_JBGerenciaProdutoActionPerformed

    private void JBCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCadastroProdutoActionPerformed
        FrmCadastroProduto telaCadastroProduto = new FrmCadastroProduto();
        telaCadastroProduto.setVisible(true);    }//GEN-LAST:event_JBCadastroProdutoActionPerformed

    private void JBCadastroMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCadastroMovimentacaoActionPerformed
        FrmCadastroMovimentacao telaCadastroMovimentacao = new FrmCadastroMovimentacao();
        telaCadastroMovimentacao.setVisible(true);
    }//GEN-LAST:event_JBCadastroMovimentacaoActionPerformed

    private void JBGerenciaMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGerenciaMovimentacaoActionPerformed
        FrmGerenciaMovimentacao telaMovimentacao = new FrmGerenciaMovimentacao();
        telaMovimentacao.setVisible(true);    }//GEN-LAST:event_JBGerenciaMovimentacaoActionPerformed

    private void JBRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRelatoriosActionPerformed
        FrmRelatorios telaRelatorios = new FrmRelatorios();
        telaRelatorios.setVisible(true);
    }//GEN-LAST:event_JBRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCadastroCategoria;
    private javax.swing.JButton JBCadastroMovimentacao;
    private javax.swing.JButton JBCadastroProduto;
    private javax.swing.JButton JBGerenciaCategoria;
    private javax.swing.JButton JBGerenciaMovimentacao;
    private javax.swing.JButton JBGerenciaProduto;
    private javax.swing.JButton JBRelatorios;
    private javax.swing.JLabel JLTitulo;
    // End of variables declaration//GEN-END:variables
}
